# Generated by Django 4.2.2 on 2023-06-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.CharField(max_length=5000, verbose_name='Image_url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='remainder',
            field=models.PositiveIntegerField(verbose_name='Remainder'),
        ),
    ]
