# Generated by Django 4.2.2 on 2023-06-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0002_alter_category_name_alter_product_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.CharField(max_length=50000, verbose_name='Image_url'),
        ),
    ]
