# Generated by Django 4.2.2 on 2023-07-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0005_itemincart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('number_phone', models.CharField(max_length=11, verbose_name='Number Phone')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('date_and_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
